//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ActionsEntry {
    
    private ActionsEntryAction[] actionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Action")]
    public ActionsEntryAction[] Action {
        get {
            return this.actionField;
        }
        set {
            this.actionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActionsEntryAction {

    private int xField;

    private int yField;
    
    private string textField;

    private int intervalField;

    private int typeField;

    //public ActionsEntryAction(int x, int y, string text, int interval, int type)
    //{
    //    this.xField = x;
    //    this.yField = x;
    //    this.textField = text;
    //    this.intervalField = interval;
    //    this.typeField = type;
    //}
    
    /// <remarks/>
    public int X {
        get {
            return this.xField;
        }
        set {
            this.xField = value;
        }
    }
    
    /// <remarks/>
    public int Y
    {
        get {
            return this.yField;
        }
        set {
            this.yField = value;
        }
    }
    
    /// <remarks/>
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    public int interval
    {
        get {
            return this.intervalField;
        }
        set {
            this.intervalField = value;
        }
    }
    
    /// <remarks/>
    public int Type
    {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
}
